# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
   
    steps:
      - name: npm-install
        uses: actions/checkout@v3
              actions/setup-node@v3
        run: npm i

      - name: npm-build        
        run: npm run build

      - name: npm-publish        
        run: npm publish
        
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
